- name: Download Java
  get_url: url={{download_url}} dest=. headers="Cookie:' gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'" validate_certs=no

- name: Install Java
  yum: name={{download_file}}

- name: Cleanup
  file: state=absent path={{download_file}}
